name = "UVH5Files"
uuid = "751b3f49-6b1d-405b-83ce-d0b609eaf806"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.0.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
DataFrames = "1.5.0"
HDF5 = "0.16.14"
julia = "1.6"
